### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by laleeroy** [borntohonk/Atmosphere#3]
Previously I can build the 1900 branch with updated switch-tools and libnx, but now at the master branch the build succeed but Im having a black screen issue right after second atmosphere logo

**Comment by borntohonk** [comment]
> Previously I can build the 1900 branch with updated switch-tools and libnx, but now at the master branch the build succeed but Im having a black screen issue right after second atmosphere logo

https://github.com/borntohonk/Atmosphere/releases/tag/19.0.0-1.8.0-753d1cc0e

everything you need to know is there, in the release information, it says what commits, of what is used.

use the same libnx for the same result

git clone https://github.com/Atmosphere-NX/libnx.git
cd libnx
git checkout 1900_support
make install

**Comment by borntohonk** [comment]
Alternatively just use the compiled binaries from my release, which boots fine on my console.

**Comment by borntohonk** [comment]
I will consider parsing build steps for the releases in the future, most probably by linking to https://github.com/borntohonk/suppository and having the actual instructions there, with the target being the docker container

**Comment by laleeroy** [comment]
> I will consider parsing build steps for the releases in the future, most probably by linking to https://github.com/borntohonk/suppository and having the actual instructions there, with the target being the docker container

Oh yeah it's the libnx, I forgot that I reinstalled it from pacman packages, anyway thanks for your work man!

**Comment by laleeroy** [comment]
> I will consider parsing build steps for the releases in the future, most probably by linking to https://github.com/borntohonk/suppository and having the actual instructions there, with the target being the docker container (originally i had said repository contain git actions to automate and publish builds here with cross-repository permissions)

Cool! I didn't know it exist until just now, I will be using this soon for github actions, thanks!

**Comment by borntohonk** [comment]
> > I will consider parsing build steps for the releases in the future, most probably by linking to https://github.com/borntohonk/suppository and having the actual instructions there, with the target being the docker container (originally i had said repository contain git actions to automate and publish builds here with cross-repository permissions)
> 
> Cool! I didn't know it exist until just now, I will be using this soon for github actions, thanks!

I need to touch it up again before its ready for that, will probably redo it soon

**Comment by borntohonk** [comment]
@laleeroy 

I have re-added a git workflow to suppository; https://github.com/borntohonk/suppository/blob/master/.github/workflows/build.yml

to deploy it to suppository you'd just change https://github.com/borntohonk/suppository/blob/master/.github/workflows/build.yml#L149 to your fork of suppository instead of borntohonk/atmosphere

to deploy it to your fork of atmosphere, you have to add a private token with repo permissions under gh_token within a fork of suppository.

i've already updated suppository docker container usage instructions within https://github.com/borntohonk/suppository/blob/master/README.md


i have a test workflow running about now, and if i recall correctly running a compile of atmosphere on git actions without private runners takes about 1-2 hours.
https://github.com/borntohonk/suppository/actions/runs/11367085431

**Comment by laleeroy** [comment]
> @laleeroy
> 
> I have re-added a git workflow to suppository; https://github.com/borntohonk/suppository/blob/master/.github/workflows/build.yml
> 
> to deploy it to suppository you'd just change https://github.com/borntohonk/suppository/blob/master/.github/workflows/build.yml#L149 to your fork of suppository instead of `--repo github.com/borntohonk/Atmosphere`
> 
> to deploy it to your fork of atmosphere, you have to add a private token with repo permissions under gh_token within a fork of suppository.
> 
> i've already updated suppository docker container usage instructions within https://github.com/borntohonk/suppository/blob/master/README.md
> 
> i have a test workflow running about now, and if i recall correctly running a compile of atmosphere on git actions without private runners takes about 1-2 hours. https://github.com/borntohonk/suppository/actions/runs/11367284556

That was fast! Will check it out later.

**Comment by borntohonk** [comment]
> > @laleeroy
> > I have re-added a git workflow to suppository; https://github.com/borntohonk/suppository/blob/master/.github/workflows/build.yml
> > to deploy it to suppository you'd just change https://github.com/borntohonk/suppository/blob/master/.github/workflows/build.yml#L149 to your fork of suppository instead of `--repo github.com/borntohonk/Atmosphere`
> > to deploy it to your fork of atmosphere, you have to add a private token with repo permissions under gh_token within a fork of suppository.
> > i've already updated suppository docker container usage instructions within https://github.com/borntohonk/suppository/blob/master/README.md
> > i have a test workflow running about now, and if i recall correctly running a compile of atmosphere on git actions without private runners takes about 1-2 hours. https://github.com/borntohonk/suppository/actions/runs/11367284556
> 
> That was fast! Will check it out later.

it's fast because i had some remnants of this project offline and have done this before, just have done this locally on a private server and just haven't bothered re-adding it.

**Comment by laleeroy** [comment]
Got it, Thanks!

**Comment by borntohonk** [comment]
Seems build time is about 20 minutes actually, which is a surprise to me.

**Comment by borntohonk** [comment]
@laleeroy took some fine tuning, but the suppository repository now contains a functioning git workflow, which both uploads an artifact to the suppository repository, and has the capability to publish to other repositories if GH_TOKEN is set under "/settings/secrets/actions"

https://github.com/borntohonk/Atmosphere/releases/tag/19.0.0-1.8.0-753d1cc0e
https://github.com/borntohonk/suppository/actions/runs/11372831094

**Comment by laleeroy** [comment]
> Seems build time is about 20 minutes actually, which is a surprise to me. (also dkp-pacman run cannot be done, rip) ,
> 
> testing to see if it'll upload an artifact, after that im done playing with this

**Comment by laleeroy** [comment]
> Seems build time is about 20 minutes actually, which is a surprise to me. (also dkp-pacman run cannot be done, rip) ,
> 
> testing to see if it'll upload an artifact, after that im done playing with this

> Seems build time is about 20 minutes actually, which is a surprise to me. (also dkp-pacman run cannot be done, rip) ,
> 
> testing to see if it'll upload an artifact, after that im done playing with this

Nice 20mins! My previous docker image that I used took like about 30mins, no troposphere stuffs in source code.
